#!/bin/bash

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, you may
#       specify it by setting the SHELL variable when running this script.
#       Example: SHELL=/bin/ksh ./gradlew <args>
#
#   (2) The scripts will be placed in the bin folder by the default location.
#
#   (3) Decide the Java location by setting the JAVA_HOME variable in your
#       environment. It overrides the JAVA_HOME instruction set almost all unix
#       shells.
#
#   (4) You can set Gradle to use the Java compiler of your choice:
#       Example: ./gradlew -java-home /path/to/java/home <args>
#
##############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`
APP_HOME="`pwd -P`"
CLASSPATH="`dirname \"$APP_HOME\"`/gradle/wrapper/gradle-wrapper.jar"

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

ORIGINAL_IFS=$IFS
IFS=$'\n'
for arg in "$@" ; do
  IFS=$ORIGINAL_IFS
  case $arg in
    -.*) false;;
    *  ) break;;
  esac
done
IFS=$ORIGINAL_IFS
set -- "$args"

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`

    JAVACMD=`cygpath --unix "$JAVACMD"`

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=`find -L / -maxdepth 3 -type d -name java >/dev/null 2>&1 && echo "ROOTDIR"` || true
    if [ -n "$ROOTDIRSRAW" ] ; then
        ROOTDIRS=`echo "$ROOTDIRSRAW" | awk 'BEGIN { FS=" " } { for (i=1; i<=NF; i++) print $1 }'`
        for dir in $ROOTDIRS ; do
            if [ -d "$dir/bin" ] ; then
                JAVACMD=`cygpath --unix "$dir/bin/java"`
                break
            fi
        done
    fi
else
    JAVACMD=`which java`
    [ -z "$JAVACMD" ] && FATAL "java not found in your PATH. Please set the JAVA_HOME variable in your environment, pointing to the location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$msys" = "false" ] && ! [ "$nonstop" = "true" ] ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
    JAVACMD=`cygpath --unix "$JAVACMD"`

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=`find -L / -maxdepth 3 -type d -name java >/dev/null 2>&1 && echo "ROOTDIR"` || true
    if [ -n "$ROOTDIRSRAW" ] ; then
        ROOTDIRS=`echo "$ROOTDIRSRAW" | awk 'BEGIN { FS=" " } { for (i=1; i<=NF; i++) print $1 }'`
        for dir in $ROOTDIRS ; do
            if [ -d "$dir/bin" ] ; then
                JAVACMD=`cygpath --unix "$dir/bin/java"`
                break
            fi
        done
    fi
fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
    echo " "
}
APP_ARGS=`save "$@"`

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval "set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \"-Dorg.gradle.appname=$APP_BASE_NAME\" -classpath \"$CLASSPATH\" org.gradle.wrapper.GradleWrapperMain \"$APP_ARGS\""

exec "$JAVACMD" "$@"
